// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2CzK16ZTps4g8KZHCQWsuix20U6EkQyI',
    appId: '1:451256250756:web:a54e12d009a3891146edd1',
    messagingSenderId: '451256250756',
    projectId: 'chat-app-1eaac',
    authDomain: 'chat-app-1eaac.firebaseapp.com',
    storageBucket: 'chat-app-1eaac.firebasestorage.app',
    measurementId: 'G-GLYQ99KB83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6THMbmZJsHJ8R5dFoTHNLcFoS5zEbqQ0',
    appId: '1:451256250756:android:f7d794e1c274c1dd46edd1',
    messagingSenderId: '451256250756',
    projectId: 'chat-app-1eaac',
    storageBucket: 'chat-app-1eaac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQeq5qOyGuuzzieDXIG-5Bv8pwF-Zk_I',
    appId: '1:451256250756:ios:4e898e68f171555046edd1',
    messagingSenderId: '451256250756',
    projectId: 'chat-app-1eaac',
    storageBucket: 'chat-app-1eaac.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAQeq5qOyGuuzzieDXIG-5Bv8pwF-Zk_I',
    appId: '1:451256250756:ios:4e898e68f171555046edd1',
    messagingSenderId: '451256250756',
    projectId: 'chat-app-1eaac',
    storageBucket: 'chat-app-1eaac.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2CzK16ZTps4g8KZHCQWsuix20U6EkQyI',
    appId: '1:451256250756:web:4f20817351d14ac746edd1',
    messagingSenderId: '451256250756',
    projectId: 'chat-app-1eaac',
    authDomain: 'chat-app-1eaac.firebaseapp.com',
    storageBucket: 'chat-app-1eaac.firebasestorage.app',
    measurementId: 'G-59Q8KTDFTZ',
  );
}
